version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"
  jobs:
    post_install:
      - pip install sphinx_mdinclude
      - pip install sphinx-rtd-theme

sphinx:
  configuration: docs/conf.py
